#!/bin/bash

set -e

DIST=$(git rev-parse --show-toplevel)/packages/angular/dist

yarn run ng build --source-map=false

cat "$DIST/SampleWebComponent/polyfills.js" \
	<(echo) \
	"$DIST/SampleWebComponent/vendor.js" \
	<(echo) \
	"$DIST/SampleWebComponent/runtime.js" \
	<(echo) \
	"$DIST/SampleWebComponent/styles.js" \
	<(echo) \
	"$DIST/SampleWebComponent/main.js" > "$DIST/SampleWebComponent/bundle.js"

while (($#)); do
  if [ "$1" = "--nocommit" ]; then
    exit
  fi
  shift
done

if git diff --quiet -- "$DIST"; then
	echo 'Build finished, but there were no changes in the output.'
else
	git commit \
		-m 'chore: commit angular build artifacts (autogenerated)' \
		-- "$DIST"

	git --paginate log -1 --pretty=format:%B
fi
